export const AUTH_ERROR_CODES = {
  ACCESS_TOKEN_MISSING: "ACCESS_TOKEN_MISSING",
  INVALID_AUTHORIZATION_FORMAT: "INVALID_AUTHORIZATION_FORMAT",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  REFRESH_TOKEN_MISSING: "REFRESH_TOKEN_MISSING",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
};

export const AUTH_ERROR_MESSAGES = {
  AUTHENTICATION_REQUIRED: "Authentication is required",
  BEARER_SCHEME_REQUIRED: "Authorization must use the Bearer scheme",
  INVALID_ACCESS_TOKEN: "Invalid access token",
  ACCESS_TOKEN_EXPIRED: "Access token has expired",
  REFRESH_TOKEN_REQUIRED: "Refresh token is required",
  INVALID_REFRESH_TOKEN: "Invalid refresh token",
  REFRESH_TOKEN_EXPIRED: "Refresh token has expired",
  USER_NOT_FOUND: "The authenticated user no longer exists",
};
